[package]
name = "deque"
version = "0.1.0"
edition = "2021"
authors = ["madflash backbugkaught@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
thiserror = "1.0.31"
clap = "2.33"
