[package]
name = "deque"
version = "0.1.0"
edition = "2021"
authors = ["madflash backbugkaught@gmail.com"]

[dependencies]
anyhow = "1.0.58"
thiserror = "1.0.31"
clap = "2.33"
ansi_term = "0.12.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
